@startuml
interface IEasyTalkDbContext {
    SaveChangesAsync(cancellationToken:CancellationToken) : Task<int>
}
class "DbSet`1"<T> {
}
IEasyTalkDbContext --> "Attachments<Attachment>" "DbSet`1"
IEasyTalkDbContext --> "Dialogs<Dialog>" "DbSet`1"
IEasyTalkDbContext --> "Interests<Interest>" "DbSet`1"
IEasyTalkDbContext --> "Languages<Language>" "DbSet`1"
IEasyTalkDbContext --> "Messages<Message>" "DbSet`1"
IEasyTalkDbContext --> "Pictures<Picture>" "DbSet`1"
IEasyTalkDbContext --> "Roles<Role>" "DbSet`1"
IEasyTalkDbContext --> "Users<User>" "DbSet`1"
@enduml
