@startuml
class EasyTalkDbContext {
    + EasyTalkDbContext(options:DbContextOptions<EasyTalkDbContext>)
}
class "DbSet`1"<T> {
}
DbContext <|-- EasyTalkDbContext
IEasyTalkDbContext <|-- EasyTalkDbContext
EasyTalkDbContext --> "Attachments<Attachment>" "DbSet`1"
EasyTalkDbContext --> "Dialogs<Dialog>" "DbSet`1"
EasyTalkDbContext --> "Interests<Interest>" "DbSet`1"
EasyTalkDbContext --> "Languages<Language>" "DbSet`1"
EasyTalkDbContext --> "Messages<Message>" "DbSet`1"
EasyTalkDbContext --> "Pictures<Picture>" "DbSet`1"
EasyTalkDbContext --> "Roles<Role>" "DbSet`1"
EasyTalkDbContext --> "Users<User>" "DbSet`1"
@enduml
