@startuml
class DeleteLanguageCommandValidator {
    + DeleteLanguageCommandValidator()
}
class "AbstractValidator`1"<T> {
}
"AbstractValidator`1" "<DeleteLanguageCommand>" <|-- DeleteLanguageCommandValidator
@enduml
