@startuml
class UpdateInteresCommandValidator {
    + UpdateInteresCommandValidator()
}
class "AbstractValidator`1"<T> {
}
"AbstractValidator`1" "<UpdateInterestCommand>" <|-- UpdateInteresCommandValidator
@enduml
