@startuml
class InterestController {
    + InterestController(mediator:IMediator, mapper:IMapper)
    + <<async>> CreateInterest(request:CreateInterestDto) : Task<ActionResult<Guid>>
    + <<async>> GetAll(offset:int, limit:int) : Task<ActionResult<InterestsListViewModel>>
    + <<async>> Get(id:Guid) : Task<ActionResult<InterestLookupDto>>
    + <<async>> Delete(id:Guid) : Task<ActionResult>
    + <<async>> Update(request:UpdateInterestDto) : Task<ActionResult>
}
ControllerBase <|-- InterestController
@enduml
