@startuml
class LanguageController {
    + LanguageController(mediator:IMediator, mapper:IMapper)
    + <<async>> GetAll(offset:int, limit:int) : Task<ActionResult<LanguageListVm>>
    + <<async>> GetLanguage(id:Guid) : Task<ActionResult<LanguageDetailsVm>>
    + <<async>> AddLanguage(request:AddLanguageDto) : Task<ActionResult<Guid>>
    + <<async>> DeleteLanguage(id:Guid) : Task<ActionResult<Unit>>
    + <<async>> UpdateLanguage(request:UpdateLanguageDto) : Task<ActionResult<Unit>>
}
ControllerBase <|-- LanguageController
@enduml
