@startuml
class GetLanguagesListQueryValidator {
    + GetLanguagesListQueryValidator()
}
class "AbstractValidator`1"<T> {
}
"AbstractValidator`1" "<GetLanguagesListQuery>" <|-- GetLanguagesListQueryValidator
@enduml
