@startuml
class "ValidationBehavior`2"<TRequest,TResponse> {
    + ValidationBehavior(validators:IEnumerable<IValidator<TRequest>>)
    + Handle(request:TRequest, next:RequestHandlerDelegate<TResponse>, cancellationToken:CancellationToken) : Task<TResponse>
}
class "IPipelineBehavior`2"<T1,T2> {
}
class "IRequest`1"<T> {
}
"IPipelineBehavior`2" "<TRequest,TResponse>" <|-- "ValidationBehavior`2"
@enduml
