@startuml
class DialogConfiguration {
    + Configure(builder:EntityTypeBuilder<Dialog>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Dialog>" <|-- DialogConfiguration
@enduml
