@startuml
class LanguageConfiguration {
    + Configure(builder:EntityTypeBuilder<Language>) : void
}
class "IEntityTypeConfiguration`1"<T> {
}
"IEntityTypeConfiguration`1" "<Language>" <|-- LanguageConfiguration
@enduml
