@startuml
!include .\\EasyTalk.Application\DependencyInjection.puml
!include .\\EasyTalk.Persistence\DependencyInjection.puml
!include .\\EasyTalk.Persistence\EasyTalkDbContext.puml
!include .\\EasyTalk.WebApi\ConfigureSwaggerOptions.puml
!include .\\EasyTalk.WebApi\Program.puml
!include .\\EasyTalk.Application\Interfaces\IEasyTalkDbContext.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\AttachmentConfiguration.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\DialogConfiguration.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\InterestConfiguration.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\LanguageConfiguration.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\MessageConfiguration.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\PictureConfiguration.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\RoleConfiguration.puml
!include .\\EasyTalk.Persistence\EntityTypeConfigurations\UserConfiguration.puml
!include .\\EasyTalk.WebApi\Controllers\InterestController.puml
!include .\\EasyTalk.WebApi\Controllers\LanguageController.puml
!include .\\EasyTalk.WebApi\Middleware\CustomExceptionHandlerMiddleware.puml
!include .\\EasyTalk.WebApi\Middleware\CustomExceptionHandlerMiddlewareExtensions.puml
!include .\\EasyTalk.WebApi\Models\AddLanguageDto.puml
!include .\\EasyTalk.WebApi\Models\CreateInterestDto.puml
!include .\\EasyTalk.WebApi\Models\UpdateInterestDto.puml
!include .\\EasyTalk.WebApi\Models\UpdateLanguageDto.puml
!include .\\EasyTalks.Domain\Entities\Attachment.puml
!include .\\EasyTalks.Domain\Entities\Dialog.puml
!include .\\EasyTalks.Domain\Entities\Interest.puml
!include .\\EasyTalks.Domain\Entities\Language.puml
!include .\\EasyTalks.Domain\Entities\Message.puml
!include .\\EasyTalks.Domain\Entities\Picture.puml
!include .\\EasyTalks.Domain\Entities\Role.puml
!include .\\EasyTalks.Domain\Entities\User.puml
!include .\\EasyTalk.Application\Common\Behaviors\ValidationBehavior.puml
!include .\\EasyTalk.Application\Common\Exceptions\NotFoundException.puml
!include .\\EasyTalk.Application\Common\Mappings\AssemblyMappingProfile.puml
!include .\\EasyTalk.Application\Common\Mappings\IMapWith.puml
!include .\\EasyTalk.Application\Interests\Commands\CreateInterest\CreateInterestCommand.puml
!include .\\EasyTalk.Application\Interests\Commands\CreateInterest\CreateInterestCommandHandler.puml
!include .\\EasyTalk.Application\Interests\Commands\CreateInterest\CreateInterestCommandValidator.puml
!include .\\EasyTalk.Application\Interests\Commands\DeleteInterest\DeleteInterestCommand.puml
!include .\\EasyTalk.Application\Interests\Commands\DeleteInterest\DeleteInterestCommandHandler.puml
!include .\\EasyTalk.Application\Interests\Commands\DeleteInterest\DeleteInterestCommandValidator.puml
!include .\\EasyTalk.Application\Interests\Commands\UpdateInterest\UpdateInteresCommandHandler.puml
!include .\\EasyTalk.Application\Interests\Commands\UpdateInterest\UpdateInteresCommandValidator.puml
!include .\\EasyTalk.Application\Interests\Commands\UpdateInterest\UpdateInterestCommand.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestDetails\GetInterestDetailQuery.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestDetails\GetInterestDetailQueryHandler.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestDetails\GetInterestDetailQueryValidator.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestDetails\InterestLookupDto.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestsList\GetInterestsListQuery.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestsList\GetInterestsListQueryHandler.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestsList\InterestsListValidator.puml
!include .\\EasyTalk.Application\Interests\Queries\GetInterestsList\InterestsListViewModel.puml
!include .\\EasyTalk.Application\Languages\Commands\CreateLanguage\CreateLanguageCommand.puml
!include .\\EasyTalk.Application\Languages\Commands\CreateLanguage\CreateLanguageCommandHandler.puml
!include .\\EasyTalk.Application\Languages\Commands\CreateLanguage\CreateLanguageCommandValidator.puml
!include .\\EasyTalk.Application\Languages\Commands\DeleteLanguage\DeleteLanguageCommand.puml
!include .\\EasyTalk.Application\Languages\Commands\DeleteLanguage\DeleteLanguageCommandHandler.puml
!include .\\EasyTalk.Application\Languages\Commands\DeleteLanguage\DeleteLanguageCommandValidator.puml
!include .\\EasyTalk.Application\Languages\Commands\UpdateLanguage\UpdateLanguageCommand.puml
!include .\\EasyTalk.Application\Languages\Commands\UpdateLanguage\UpdateLanguageCommandHandler.puml
!include .\\EasyTalk.Application\Languages\Commands\UpdateLanguage\UpdateLanguageCommandValidator.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguageDetails\GetLanguageDetailsQuery.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguageDetails\GetLanguageDetailsQueryHandler.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguageDetails\GetLanguageDetailsQueryValidator.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguageDetails\LanguageDetailsVm.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguagesList\GetLanguagesListQuery.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguagesList\GetLanguagesListQueryHandler.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguagesList\GetLanguagesListQueryValidator.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguagesList\LanguageListVm.puml
!include .\\EasyTalk.Application\Languages\Queries\GetLanguagesList\LanguageLookupDto.puml
!include .\\EasyTalk.Application\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalk.Application\obj\Debug\net6.0\EasyTalk.Application.AssemblyInfo.puml
!include .\\EasyTalk.Application\obj\Debug\net6.0\EasyTalk.Application.GlobalUsings.g.puml
!include .\\EasyTalk.Application\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalk.Application\obj\Release\net6.0\EasyTalk.Application.AssemblyInfo.puml
!include .\\EasyTalk.Application\obj\Release\net6.0\EasyTalk.Application.GlobalUsings.g.puml
!include .\\EasyTalk.Persistence\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalk.Persistence\obj\Debug\net6.0\EasyTalk.Persistence.AssemblyInfo.puml
!include .\\EasyTalk.Persistence\obj\Debug\net6.0\EasyTalk.Persistence.GlobalUsings.g.puml
!include .\\EasyTalk.Persistence\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalk.Persistence\obj\Release\net6.0\EasyTalk.Persistence.AssemblyInfo.puml
!include .\\EasyTalk.Persistence\obj\Release\net6.0\EasyTalk.Persistence.GlobalUsings.g.puml
!include .\\EasyTalk.WebApi\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalk.WebApi\obj\Debug\net6.0\EasyTalk.WebApi.AssemblyInfo.puml
!include .\\EasyTalk.WebApi\obj\Debug\net6.0\EasyTalk.WebApi.GlobalUsings.g.puml
!include .\\EasyTalk.WebApi\obj\Debug\net6.0\EasyTalk.WebApi.MvcApplicationPartsAssemblyInfo.puml
!include .\\EasyTalk.WebApi\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalk.WebApi\obj\Release\net6.0\EasyTalk.WebApi.AssemblyInfo.puml
!include .\\EasyTalk.WebApi\obj\Release\net6.0\EasyTalk.WebApi.GlobalUsings.g.puml
!include .\\EasyTalks.Domain\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalks.Domain\obj\Debug\net6.0\EasyTalks.Domain.AssemblyInfo.puml
!include .\\EasyTalks.Domain\obj\Debug\net6.0\EasyTalks.Domain.GlobalUsings.g.puml
!include .\\EasyTalks.Domain\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\EasyTalks.Domain\obj\Release\net6.0\EasyTalks.Domain.AssemblyInfo.puml
!include .\\EasyTalks.Domain\obj\Release\net6.0\EasyTalks.Domain.GlobalUsings.g.puml
@enduml
