@startuml
class Attachment {
    + Label : string <<get>> <<set>>
    + Path : string <<get>> <<set>>
    + Method() : void
}
Attachment --> "Id" Guid
Attachment --> "MessageId" Guid
Attachment o-> "Message" Message
@enduml
