@startuml
class User {
    + Firstname : string <<get>> <<set>>
    + Lastname : string <<get>> <<set>>
    + Patronymic : string? <<get>> <<set>>
    + Info : string <<get>> <<set>>
    + Username : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + PhoneNumber : string <<get>> <<set>>
}
class "List`1"<T> {
}
User --> "Id" Guid
User --> "NativeLanguageId" Guid
User o-> "NativeLanguage" Language
User o-> "TargetLanguages<Language>" "List`1"
User o-> "Interests<Interest>" "List`1"
User --> "RoleId" Guid
User o-> "Role" Role
User --> "PictureId" Guid
User o-> "Picture" Picture
User o-> "Dialogs<Dialog>" "List`1"
@enduml
