@startuml
class LanguageDetailsVm {
    + LanguageName : string <<get>> <<set>>
    + Mapping(profile:Profile) : void
}
class "IMapWith`1"<T> {
}
"IMapWith`1" "<Language>" <|-- LanguageDetailsVm
LanguageDetailsVm --> "LanguageId" Guid
@enduml
